name: A workflow for my Hello World file
on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  echo1:
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '/hello')
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.event.comment.user.login }}!"
        shell: bash
      - run: echo "The issue body is ${{ github.event.comment.body }}!"
        shell: bash
      - run: echo "The branch is ${{ github.ref }}!"
        shell: bash
      - run: echo "The head ref is ${{ github.head_ref }}!"
        shell: bash
      - run: echo "PR Merge branch refs/pull/${{ github.event.issue.number }}/merge!"
        shell: bash

  dispatch_by_manual:
    if: github.event_name == 'workflow_dispatch'
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.event.comment.user.login }}!"
        shell: bash
      - run: echo "The branch is ${{ github.ref }}!"
        shell: bash
      - run: echo "The head ref is ${{ github.head_ref }}!"
        shell: bash
