name: A workflow for my Hello World file
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  issue_comment_trigger:
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '/hello')
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge
      - run: echo "Hello ${{ github.event.comment.user.login }}!"
        shell: bash
      - run: echo "The issue body is ${{ github.event.comment.body }}!"
        shell: bash
      - run: echo "The branch is ${{ github.ref }}!"
        shell: bash
      - run: echo "The head ref is ${{ github.head_ref }}!"
        shell: bash
      - run: echo "PR Merge branch refs/pull/${{ github.event.issue.number }}/merge!"
        shell: bash

  manual_trigger:
    if: github.event_name == 'workflow_dispatch'
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello ${{ github.event.comment.user.login }}!"
        shell: bash
      - run: echo "The branch is ${{ github.ref }}!"
        shell: bash
      - run: echo "The head ref is ${{ github.head_ref }}!"
        shell: bash

  pr_trigger:
    if: github.event_name == 'pull_request'
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello ${{ github.event.comment.user.login }}!"
        shell: bash
      - run: echo "The branch is ${{ github.ref }}!"
        shell: bash
      - run: echo "The head ref is ${{ github.head_ref }}!"
        shell: bash
